services:
  postgres:
    container_name: postgres-bank-america
    image: postgres
    environment:
      POSTGRES_USER: bank_of_america
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-bank
    volumes:
      - postgres-bank:/data/postgres-bank
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-bank-america
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-bank:/var/lib/pgadmin-bank
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres-bank:
    driver: bridge

volumes:
  postgres-bank:
  pgadmin-bank:
